"""F4 캐러셀 렌더링 — PRD v1.0 §5.3.

Same philosophy as sns_marketing_agent/image_generator.py: informational
cards are laid out in HTML and screenshotted, never generated by a
freeform image model (a principle the real platform's card tool explicitly
carried over from this prototype — see decisions/supernova-platform/
2026-09-18-marketing-card-design-choice.md in the fixtures).

`plan_slide_texts` is rule-based, not LLM-based, for the same reason
image_generator.py's plan_card_texts is: which text goes on which slide is
a layout decision with a fixed floor (PRD §5.3: 5-7 slides, hook first,
summary last), not a creative judgment call worth another model round-trip.
"""
from __future__ import annotations

from pathlib import Path
from typing import Protocol

from sns_marketing_agent.creative_models import CopyVariant
from sns_marketing_agent.strategy_models import Brief

ASPECTS: dict[str, tuple[int, int]] = {
    "4:5": (1080, 1350),
    "1:1": (1080, 1080),
    "9:16": (1080, 1920),
}
PRIMARY_ASPECT = "4:5"
MIN_SLIDES = 5
MAX_SLIDES = 7

_SLIDE_HTML = """<html><body style="margin:0;width:{width}px;height:{height}px;
display:flex;align-items:center;justify-content:center;background:#161513;
font-family:'Noto Sans KR',sans-serif;padding:80px;box-sizing:border-box;">
<div style="color:#f4f1ea;font-size:{font_size}px;line-height:1.4;
text-align:center;white-space:pre-wrap;">{text}</div></body></html>"""


def plan_slide_texts(variant: CopyVariant, brief: Brief) -> list[str]:
    slides: list[str] = [variant.hook]

    for message in brief.key_messages:
        if message not in slides:
            slides.append(message)

    for evidence in brief.evidence:
        if len(slides) >= MAX_SLIDES - 1:
            break
        if evidence.excerpt and evidence.excerpt not in slides:
            slides.append(evidence.excerpt)

    for filler in (brief.angle, brief.target_persona, brief.topic):
        if len(slides) >= MAX_SLIDES - 1:
            break
        if filler and filler not in slides:
            slides.append(filler)

    slides = slides[: MAX_SLIDES - 1]
    slides.append(f"{brief.topic} — 한눈에 정리")  # summary slide (PRD: CTA stays in the caption, not here)

    if not (MIN_SLIDES <= len(slides) <= MAX_SLIDES):
        raise ValueError(
            f"planned {len(slides)} slides for brief {brief.id}, need {MIN_SLIDES}-{MAX_SLIDES} "
            "(brief has too few distinct key_messages/evidence/angle/persona/topic to pad from)"
        )
    return slides


class CarouselAssetRenderer(Protocol):
    def render(self, brief_id: str, variant: int, slide_texts: list[str]) -> dict[str, list[str]]:
        """Returns {aspect: [file_path, ...]} for every aspect in ASPECTS,
        each list the same length and order as slide_texts."""
        ...


class NullCarouselRenderer:
    """Offline/test stand-in — plans without rendering, same convention as
    image_generator.NullImageGenerator (empty path = not rendered)."""

    def render(self, brief_id: str, variant: int, slide_texts: list[str]) -> dict[str, list[str]]:
        return {aspect: ["" for _ in slide_texts] for aspect in ASPECTS}


class PlaywrightCarouselRenderer:
    def __init__(self, out_dir: Path, executable_path: str | None = None):
        self._out_dir = Path(out_dir)
        self._out_dir.mkdir(parents=True, exist_ok=True)
        self._executable_path = executable_path

    def render(self, brief_id: str, variant: int, slide_texts: list[str]) -> dict[str, list[str]]:
        from playwright.sync_api import sync_playwright

        result: dict[str, list[str]] = {aspect: [] for aspect in ASPECTS}

        with sync_playwright() as p:
            browser = p.chromium.launch(executable_path=self._executable_path)
            try:
                for aspect, (width, height) in ASPECTS.items():
                    font_size = 56 if aspect == "9:16" else 48
                    page = browser.new_page(viewport={"width": width, "height": height})
                    for i, text in enumerate(slide_texts):
                        page.set_content(
                            _SLIDE_HTML.format(width=width, height=height, font_size=font_size, text=text)
                        )
                        aspect_slug = aspect.replace(":", "x")
                        out_path = (
                            self._out_dir / f"{brief_id}_v{variant}_{aspect_slug}_{i}.png"
                        )
                        page.screenshot(path=str(out_path))
                        result[aspect].append(str(out_path))
                    page.close()
            finally:
                browser.close()

        return result
